import type { Metadata } from "next";
//import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/Nav";
import { geistMono, geistSans  } from "@/utils/fonts";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const openSans = Open_Sans({
//   subsets: ['latin'],
//   display: 'swap'  
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
